# Generated by Django 4.0.4 on 2022-04-26 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_alter_subject_options_subject_code_and_more'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'PREGUNTA', 'verbose_name_plural': 'PREGUNTAS'},
        ),
        migrations.AddField(
            model_name='questions',
            name='code',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='subject.subject'),
        ),
    ]
