# Generated by Django 4.0.4 on 2022-04-26 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_questions_options_questions_code_and_more'),
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name': 'RESPUESTA', 'verbose_name_plural': 'RESPUESTAS'},
        ),
        migrations.AddField(
            model_name='answers',
            name='code',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers',
            name='questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='questions.questions'),
        ),
    ]
