# Generated by Django 4.0.4 on 2022-04-26 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'verbose_name': 'FORO', 'verbose_name_plural': 'FOROS'},
        ),
        migrations.AddField(
            model_name='forum',
            name='discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='forum', to='discussion.discussion'),
        ),
    ]
