# Generated by Django 4.0.4 on 2022-04-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_alter_forum_options_forum_discussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='discussion',
        ),
        migrations.AddField(
            model_name='forum',
            name='code',
            field=models.CharField(default=11, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
