# Generated by Django 4.0.4 on 2022-04-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_discussion_code_discussion_forum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'verbose_name': 'DISCUSION', 'verbose_name_plural': 'DISCUCIONES'},
        ),
    ]
